# -*- coding: utf-8 -*-
"""Setting up the environment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJPzcjIuGqvOIwOJf3mDu69iyE1TBuos
"""

### script.py

```python
!pip install -q kaggle
from google.colab import files
# Upload kaggle.json file from kaggle
files.upload()

!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets list
!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

import torch
from torch import nn

import requests
import zipfile
from pathlib import Path

data_path = Path('data/')
image_path = data_path / 'chest-xray-pneumonia'

if image_path.is_dir():
    print(f'{image_path} directory already exists...skipping download')
else:
    print(f'{image_path} does not exist, creating one...')
    image_path.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(data_path / 'chest-xray-pneumonia.zip', 'r') as zip_ref:
    print('Extracting chest-xray-pneumonia data...')
    zip_ref.extractall(image_path)

data_path / 'chest-xray-pneumonia.zip'
image_path

import os
def walk_through_dir(dir_path):
    for dirpath, dirnames, filenames in os.walk(dir_path):
        print(f'There are {len(dirnames)} directories and {len(filenames)} images in {dirpath}')

train_dir = image_path / 'train'
test_dir = image_path / 'test'
val_dir = image_path / 'val'
train_dir, test_dir, val_dir

import random
from PIL import Image

random.seed(42)
image_path_list = list(image_path.glob('*/*/*.jpeg'))

random_image_path = random.choice(image_path_list)
print(random_image_path)

image_class = random_image_path.parent.stem
print(image_class)
img = Image.open(random_image_path)
print(f'Random image path: {random_image_path}')
print(f'Image class: {image_class}')
print(f'Image height: {img.height}')
print(f'Image width: {img.width}')
img